title: DevSphere
email: miguelportillo2475@gmail.com
description: >- 
  Repositorio técnico con guías, clases de desarrollo y otras tecnologías.
permalink: /:title/
baseurl: "" 
url: "https://miguelp-dev.github.io"
github_username: Miguelp-Dev
logo: /assets/images/logo.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sass-converter
  - kramdown-parser-gfm
  - jekyll-mermaid

mermaid:
  enabled: true
  version: "latest"
  theme: "base" # Usamos 'base' porque personalizamos con CSS

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Collections configuration
collections:
  sections:
    output: true
    permalink: /:collection/:name/
  packages:
    output: true
    permalink: /packages/:name/
  examples:
    output: true
    permalink: /examples/:name/
  technologies:
    output: true
    permalink: /technologies/:name/
  cheatsheets:
    output: true
    permalink: /cheat_sheets/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_sections"
      type: "sections"
    values:
      layout: section
  - scope:
      path: "_packages"
      type: "packages"
    values:
      layout: section
      category: packages
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: section
      category: examples
  - scope:
      path: "_technologies"
      type: "technologies"
    values:
      layout: section
      category: technologies
  - scope:
      path: "_cheat_sheets"
      type: "cheatsheets"
    values:
      layout: section
      category: cheatsheets

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

include:
#   - _data
#   - _layouts
#   - _includes
- assets
- _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
